<?php

namespace Modules\Ticket\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('employee')->insert([
            ['employee_name' => 'JOHNY ALEXANDER VASQUEZ GARCIA', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'OSCAR SATURNINO ALFARO CASCO', 'employee_area' => 'GERENCIA DE RECURSOS HUMANOS', 'status' => 1],
            ['employee_name' => 'WILLIAM MARROQUIN', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'JUAN CARLOS SANTOS VALENCIA', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'EDENILSON VLADIMIR MENDOZA BRIZUELA', 'employee_area' => 'GERENCIA DE RECURSOS HUMANOS', 'status' => 1],
            ['employee_name' => 'WALTER ANTONIO LAINEZ LOPEZ', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'SAUL FRANCISCO LARREYNAGA ANAYA', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'CARLOS ROBERTO LOPEZ POCASANGRE', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'DANIEL RODOLFO RODRIGUEZ LEIVA', 'employee_area' => 'GERENCIA DE RECURSOS HUMANOS', 'status' => 1],
            ['employee_name' => 'JESUS ALBERTO PINEDA HERNANDEZ', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'JOSE EDUARDO MENJIVAR COREAS', 'employee_area' => 'GERENCIA DE RECURSOS HUMANOS', 'status' => 1],
            ['employee_name' => 'GERSON ALBERTO SORIANO ROMERO', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'PEDRO ORLANDO ALVAREZ MENJIVAR', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'ANA MARGARITA URRUTIA PINEDA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'ROSALBA MARISELA LEMUS DE GIRON', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'CLAUDINA PAULETTE MARTINEZ PEREZ', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'CARLOS ENRIQUE CANALES LOPEZ', 'employee_area' => 'UNIDAD DE INFORMATICA', 'status' => 1],
            ['employee_name' => 'MARIA JOSEFA CAMPOS DE VIDES', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'HECTOR DANIEL GARCIA MENA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'TATIANA VANESSA NAVARRO DE GONZALEZ', 'employee_area' => 'GERENCIA DE RECURSOS HUMANOS', 'status' => 1],
            ['employee_name' => 'ANGIE MELISSA ALFARO CRUZ', 'employee_area' => 'GERENCIA DE VENTAS', 'status' => 1],
            ['employee_name' => 'THUEDY JAVIER FLORES FUENTES', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'JESUS EMILIO RODRIGUEZ PICHE', 'employee_area' => 'UNIDAD DE INFORMATICA', 'status' => 1],
            ['employee_name' => 'CARLA DINELY CEDILLOS ZEPEDA', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'OSCAR ERNESTO SOLITO', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'MARCELA SOFIA OCHOA AMAYA', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'RENE SAUL SOSA ALAS', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'JAVIER EDUARDO MENDOZA ALCANTARA', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'LISBETH KARINA VALLADARES GARCIA', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'NOE ANTONIO DIAZ ZEPEDA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'MARIO ANTONIO BARRAZA FLORES', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'NANCY YAMICEL PENIA DE GALVAN', 'employee_area' => 'UNIDAD DE COMPRAS PUBLICAS', 'status' => 1],
            ['employee_name' => 'JUAN ANTONIO OLIVO RODRIGUEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'RODRIGO ERNESTO GRANADOS RODRIGUEZ', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'MARLON ANTHONY RAMOS ARTIGA', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'RAUL ANTONIO CASTRO DOMINGUEZ', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'GUSTAVO EDUARDO ACEVEDO ULLOA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'ELIO ENRIQUE CASTELLON TORRES', 'employee_area' => 'UNIDAD DE INFORMATICA', 'status' => 1],
            ['employee_name' => 'RAFAEL ANTONIO AYALA AYALA', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'CRISTOPHER GUILLERMO GONZALEZ MORAN', 'employee_area' => 'GERENCIA DE PROYECTOS', 'status' => 1],
            ['employee_name' => 'VERONICA ANTONIA DURAN DE GALVEZ', 'employee_area' => 'UNIDAD DE PLANIFICACION', 'status' => 1],
            ['employee_name' => 'VICTOR ANTONIO PADILLA', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'KEVIN ERNESTO ESTRADA HERNANDEZ', 'employee_area' => 'UNIDAD DE COMPRAS PUBLICAS', 'status' => 1],
            ['employee_name' => 'ROBERTO ENRIQUE MORENO VILLANUEVA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'WALTER JEOVANNI ROSALES VALLE', 'employee_area' => 'GERENCIA DE PROYECTOS', 'status' => 1],
            ['employee_name' => 'WILFREDO PINEDA AYALA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'ALEJANDRA MARIA VEGA TENORIO', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'ALICIA LIZETH AGUILAR LINO', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'CRISTINA MARIA SANTOS ORELLANA', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'MARVIN ANTONIO RAMIREZ', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'JOSE MARCO OSTORGA DURAN', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'KEVIN ESAU ALEMAN ALFARO', 'employee_area' => 'GERENCIA DE PROYECTOS', 'status' => 1],
            ['employee_name' => 'ALEJANDRA MICHELLE PORTILLO DE ELIAS', 'employee_area' => 'GERENCIA DE BANQUETES', 'status' => 1],
            ['employee_name' => 'JAIME EDGARDO MONTALVO ALVAREZ', 'employee_area' => 'GERENCIA DE BANQUETES', 'status' => 1],
            ['employee_name' => 'JOSE ANDRES LOBO MIRANDA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'JOSE ROBERTO RECINOS RODRIGUEZ', 'employee_area' => 'UNIDAD DE COMPRAS PUBLICAS', 'status' => 1],
            ['employee_name' => 'FELIX ANTONIO VICTORIANO CORDERO', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'CELIA ALEXANDRA VENTURA MELENDEZ', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'JOSE JOAQUIN SANCHEZ AMAYA', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'HECTOR JOSE VELASQUEZ AGUILAR', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'FREDY ALONSO MENDOZA HERRERA', 'employee_area' => 'GERENCIA DE BANQUETES', 'status' => 1],
            ['employee_name' => 'JOSE ANDRES MENENDEZ DIAZ', 'employee_area' => 'GERENCIA LEGAL', 'status' => 1],
            ['employee_name' => 'MARLON ANTONIO VALLE RAMIREZ', 'employee_area' => 'PRESIDENCIA', 'status' => 1],
            ['employee_name' => 'JOSE ISMAEL GARCIA HERNANDEZ', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'YOLANDA DEL CARMEN HENRIQUEZ ROSALES', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'JACQUELINE ELIZABETH MEZQUITA MEJIA', 'employee_area' => 'GERENCIA LEGAL', 'status' => 1],
            ['employee_name' => 'EMERITA YASMIN ALVARADO DE BELTRAN', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'GEOVANY ELEAZAR PORTILLO LEIVA', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'SILVIA REBECA GALLARDO CASTILLO', 'employee_area' => 'DIRECCION ADMINISTRATIVA FINANCIERA', 'status' => 1],
            ['employee_name' => 'BRYAN ROBERTO AVILES RECINOS', 'employee_area' => 'GERENCIA DE PROYECTOS', 'status' => 1],
            ['employee_name' => 'WALTER VASQUEZ RIVAS', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'DENIS JOSUE PORTILLO ABARCA', 'employee_area' => 'GERENCIA DE VENTAS', 'status' => 1],
            ['employee_name' => 'FREDY ALEXANDER BARAHONA MIRANDA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'ALMA BEATRIZ RAMIREZ ABREGO', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'STEVEN GIOVANNI RIVERA RODRIGUEZ', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'HUGO ARMANDO GUTIERREZ HIDALGO', 'employee_area' => 'GERENCIA ADMINISTRATIVA', 'status' => 1],
            ['employee_name' => 'REYES BALTAZAR MEJIA HERNANDEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'MARVIN DAVID ASCENCIO BERNAL', 'employee_area' => 'GERENCIA DE MERCADEO', 'status' => 1],
            ['employee_name' => 'RONALD FRANCISCO CABRERA SALAZAR', 'employee_area' => 'AUDITORIA INTERNA', 'status' => 1],
            ['employee_name' => 'SILVIA MARISOL GUEVARA DE MERINO', 'employee_area' => 'GERENCIA LEGAL', 'status' => 1],
            ['employee_name' => 'CARLOS ENRIQUE GARAY', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'DAVID ERNESTO CASTILLO CHAVEZ', 'employee_area' => 'GERENCIA DE BANQUETES', 'status' => 1],
            ['employee_name' => 'EDGAR DANILO MENDOZA VASQUEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'EDWIN OSWALDO SANCHEZ MAURICIO', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'GERSON EDUARDO GARCIA MENDOZA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JAVIER ERNESTO LEIVA VALIENTE', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'JESUS ANTONIO GARCIA SANCHEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JIMMY FRANKLYN ALVARADO RODRIGUEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JONATHAN DE JESUS VILLANUEVA VALLADARES', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'JORGE ALBERTO ERAZO ERAZO', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JOSE JHONY MARTINEZ', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JOSE LUIS AGUILAR RIVAS', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JOSE NEHEMIAS RAMOS MANCIA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'KARLA LIZBETH VELASQUEZ COTO', 'employee_area' => 'GERENCIA DE PROYECTOS', 'status' => 1],
            ['employee_name' => 'KEVIN JOSUE SALINAS HERNANDEZ', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'LORENA DANIELA CHAVEZ AGUILAR', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'MARLON ENRIQUE BARRIOS GUZMAN', 'employee_area' => 'GERENCIA DE BANQUETES', 'status' => 1],
            ['employee_name' => 'RENE ARNOLDO LEMUS RODRIGUEZ', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'ROSARIO DEL CARMEN MENDEZ LOPEZ', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'WALTER CESAR PARADA AGUILAR', 'employee_area' => 'SEGURIDAD', 'status' => 1],
            ['employee_name' => 'WALTHER ANTONIO SOSA RIVERA', 'employee_area' => 'GERENCIA DE OPERACIONES', 'status' => 1],
            ['employee_name' => 'JOSUE ISAAC AYALA ABREGO', 'employee_area' => 'UNIDAD DE INFORMATICA', 'status' => 1],
            ['employee_name' => 'CLIENTES', 'employee_area' => 'CLIENTES', 'status' => 1],
        ]);
    }
}
